### Numpy
used to perform mathmatical and logical operations on arrays.  


In [3]:
import numpy as np
np.random.randint(0,10,4) # random values gengerates like opt 

array([2, 2, 0, 1])

In [3]:
import numpy as np
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.full((4,4),2)# we can give any value in last

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [15]:
#1D array
a=np.array([2,3,5])
print(a)

[2 3 5]


In [16]:
a=np.array([23,5,67,12,45])
print(a)
a.ndim

[23  5 67 12 45]


1

In [29]:
#2D array
a=np.array([[3,5,4],[2,2,2],[2,1,3]])
print(a)
print(a.ndim)
print(a.shape)

[[3 5 4]
 [2 2 2]
 [2 1 3]]
2
(3, 3)


In [27]:
b=np.array([[1,4,6],[5,9,3]])
print(b)
print(b.ndim)
print(b.shape)

[[1 4 6]
 [5 9 3]]
2
(2, 3)


In [71]:
c=np.array([[[1,2,3],[3,2,1],[3,6,4]],[[3,4,5],[9,6,7],[1,2,3]]])
print(c)
print(c.ndim)
print(c.shape)
print(c.size) # number of elements present in a array

[[[1 2 3]
  [3 2 1]
  [3 6 4]]

 [[3 4 5]
  [9 6 7]
  [1 2 3]]]
3
(2, 3, 3)
18


In [27]:
np.arange(0,51,5) # 5=intervel

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [33]:
np.linspace(10,20,4) # initialize z number between x and y

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [37]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [119]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [95]:
a=np.array([[2,4,5,6],[1,6,3,7],[9,7,4,1]])
print("original Array",a)
a.shape=(6,2)
print("changed array",a)
a.shape=(1,12)
print("changed array",a)
a.shape=(4,3)
print("changed array",a)
print(a.ndim)
a.shape=(2,3,2)
print(a)
print(a.ndim)
print(a.shape)

original Array [[2 4 5 6]
 [1 6 3 7]
 [9 7 4 1]]
changed array [[2 4]
 [5 6]
 [1 6]
 [3 7]
 [9 7]
 [4 1]]
changed array [[2 4 5 6 1 6 3 7 9 7 4 1]]
changed array [[2 4 5]
 [6 1 6]
 [3 7 9]
 [7 4 1]]
2
[[[2 4]
  [5 6]
  [1 6]]

 [[3 7]
  [9 7]
  [4 1]]]
3
(2, 3, 2)


In [69]:
b=np.array([[1,2,3],[4,5,6],[5,8,8],[5,6,4]])
print(b.size) # size means 4 rows * 3 columns=12, 


12


In [30]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.full((4,5),-6)

array([[-6, -6, -6, -6, -6],
       [-6, -6, -6, -6, -6],
       [-6, -6, -6, -6, -6],
       [-6, -6, -6, -6, -6]])

In [7]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.arange(20,50,5)

array([20, 25, 30, 35, 40, 45])

In [23]:
np.linspace(2,25,10)

array([ 2.        ,  4.55555556,  7.11111111,  9.66666667, 12.22222222,
       14.77777778, 17.33333333, 19.88888889, 22.44444444, 25.        ])

In [133]:
z=np.arange(20)
print(z)
print(z.ndim)
print(z.shape)
np.sum(z)
np.max(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
1
(20,)


19

In [153]:
# converting 1d to 3d
z.shape=(2,5,2)
print(z)
print(z.ndim)
print(z.shape)
np.max(z)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
3
(2, 5, 2)


19

In [83]:
# conerting 1d to 2d
z.shape=(5,4)
print(z)
print(z.ndim)
print(z.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
2
(5, 4)


In [125]:
y=np.array([[[[1,3,2],[2,3,4]],[[3,4,5],[2,5,3]]]])
print(y)
print(y.ndim)
print(y.shape)

[[[[1 3 2]
   [2 3 4]]

  [[3 4 5]
   [2 5 3]]]]
4
(1, 2, 2, 3)


In [85]:
import numpy as np
x=np.random.randint(0,20,(6,5))
print(x)

[[18 18 12 17  2]
 [16 13 10  3 13]
 [ 4 14 13  3 14]
 [11 16 15 14  8]
 [18 15 13 10  0]
 [ 4  3  8 12  5]]


In [87]:
x.shape=(2,15)
print(x)

[[18 18 12 17  2 16 13 10  3 13  4 14 13  3 14]
 [11 16 15 14  8 18 15 13 10  0  4  3  8 12  5]]


In [7]:
y=x.ravel()

In [9]:
y.reshape(10,3)

array([[ 1, 13, 13],
       [ 9,  9, 14],
       [14, 19,  6],
       [13, 14, 15],
       [ 0, 11,  2],
       [12, 19, 19],
       [14, 19,  4],
       [ 1, 12, 10],
       [ 2,  7,  3],
       [18,  3, 14]])

In [25]:
print(y)

[ 1 13 13  9  9 14 14 19  6 13 14 15  0 11  2 12 19 19 14 19  4  1 12 10
  2  7  3 18  3 14]


In [91]:
x1=np.array([[2,3],[4,3]])

In [93]:
x2=np.array([[4,5],[6,7]])

In [35]:
np.vstack([x1,x2])

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [37]:
np.hstack([x1,x2])

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [95]:
np.concatenate([x1,x2],axis=0)

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [97]:
np.concatenate([x1,x2],axis=1)

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [41]:
x=([[2,3,4],[2,5,7]])
np.sum(x)

23

In [39]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[10,11,12]])
sum_array=array1+array2
print("addition",sum_array)

addition [[ 8 10 12]
 [14 16 18]]


In [53]:
sub=np.subtract(20,16) # it will take two arguments
print(sub)

4


### broad casting

In [55]:
a=np.array([[2,3],[1,5]]) # using defferent shapes(broadcasting)
b=np.array([[5,4]])
add=a+b
print(add)

[[7 7]
 [6 9]]


### Numpy Mathematical Functions

In [1]:
# Arithmetic functions
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
print(np.add(a,2))
print(np.subtract(a,1))
print(np.multiply(a,2))
print(np.divide(a,2))
print(np.power(a,2))

[ 2  3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7  8]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  1  4  9 16 25 36 49 64 81]


In [55]:
x=np.array([[9,8,7],[6,5,4]])
y=np.array([[1,2,3],[4,5,6]])
z=x+y
print(z)

[[10 10 10]
 [10 10 10]]


In [75]:
print('1',np.add(x,y))
print('2',np.subtract(x,y))
print('3',np.multiply(x,y))
print('4',np.divide(x,y))
print('5',np.power(x,y))

1 [[10 10 10]
 [10 10 10]]
2 [[ 8  6  4]
 [ 2  0 -2]]
3 [[ 9 16 21]
 [24 25 24]]
4 [[9.         4.         2.33333333]
 [1.5        1.         0.66666667]]
5 [[   9   64  343]
 [1296 3125 4096]]


In [79]:
#Rounding function
x=np.array([1.8,2.3,4.5,6.9,4])
print(np.round(x))
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))

[2. 2. 4. 7. 4.]
[1. 2. 4. 6. 4.]
[2. 3. 5. 7. 4.]
[1. 2. 4. 6. 4.]


In [81]:
# aggregate functions
print(np.sum(x))
print(np.max(x))
print(np.min(x))

19.5
6.9
1.8


In [19]:
a=np.array([1,2,4,2,1,3,3])
print("sum",np.sum(a))
print("count",np.size(a))
print("mean",np.mean(a))
print("median",np.median(a))
print("correlation coefficient",np.corrcoef(a))
print("standard deviation",np.std(a))

sum 16
count 7
mean 2.2857142857142856
median 2.0
correlation coefficient 1.0
standard deviation 1.0301575072754257


In [9]:
import numpy as np
g=np.array([2,5,3])
h=np.array([6,8,9])
j=h*g
print(j)

[12 40 27]


In [115]:
print(np.sum(j))
print(np.max(j))

33
13


In [5]:
s=np.array([2,3])
d=np.array([1,8])
result=s*d
print(result)

[ 2 24]


#### Exponential

In [10]:
a=np.array([1,2,3,4,5])
exp_a=np.exp(a)
print(exp_a)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [18]:
a=np.array([1,4,9,16,25])
print(a)
squareroot=np.sqrt(a)
print(squareroot)

[ 1  4  9 16 25]
[1. 2. 3. 4. 5.]


In [20]:
np.sin(a)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175])

In [22]:
np.cos(a)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948,  0.99120281])

In [24]:
np.log(a)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582])

### numpy matrix multiplication

In [1]:
import numpy as np
x1=np.random.randint(0,10,(2,3))
x2=np.random.randint(0,10,(3,2))
print(x1)
print(x2)

[[0 5 1]
 [2 5 8]]
[[0 1]
 [5 1]
 [2 2]]


In [3]:
print(np.dot(x1,x2))

[[27  7]
 [41 23]]


### indexing and slicing in python

In [14]:
a=['p','y','','t','h','o','n']
a[1:6]

['y', '', 't', 'h', 'o']

In [42]:
a=np.array([[1,4,2],[5,1,3],[9,4,5]])
print(a[:2])
print(a[1:,1:])
print(a[2,2])

[[1 4 2]
 [5 1 3]]
[[1 3]
 [4 5]]
5


In [50]:
print(np.sum([[[1,2,3],[4,1,3]],[[7,1,5],[4,3,2]]],axis=0)) # sum the columns
print(np.sum([[[1,2,3],[4,1,3]],[[7,1,5],[4,3,2]]],axis=1)) # sum the rows

[[8 3 8]
 [8 4 5]]
[[ 5  3  6]
 [11  4  7]]


In [60]:
a=np.array([5,3])
b=np.array([2,5])
print(np.sum(b))
print(np.sum(a))

7
8
